---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  remote_user: deploy

  tasks:
    - name: Clone/pull project repo
      git: repo={{ repository }}
           dest={{ install_path }}/{{ project_name }}/app
           accept_hostkey=yes
      notify:
      - restart gunicorn
    
    - name: Delete all .pyc files
      command: find . -name '*.pyc' -delete
      args:
        chdir: "{{ install_path }}/{{ project_name }}/app"
      changed_when: False

    - name: Install python packages
      pip:
        requirements: "{{ install_path }}/{{ project_name }}/app/requirements.txt"
        virtualenv: "{{ install_path }}/{{ project_name }}/env"
        virtualenv_python: pypy
      notify:
      - restart gunicorn

    - name: make sure nginx server is running
      service: name=nginx state=started enabled=yes use=service

    - name: make sure gunicorn server is running
      service: name=nginx state=started enabled=yes use=service
    
    - name: make sure huey consumer is running
      service: name=nginx state=started enabled=yes use=service

  handlers: 
    - name: restart nginx
      service: name=nginx state=reload enabled=yes use=service

    - name: restart gunicorn
      service: name=nginx state=restarted enabled=yes use=service
    
    - name: restart huey
      service: name=nginx state=started enabled=yes use=service
